# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OPS <- function(n, prop) {
    .Call(`_jra_OPS`, n, prop)
}

ker_r <- function(u) {
    .Call(`_jra_ker_r`, u)
}

ker_l <- function(u) {
    .Call(`_jra_ker_l`, u)
}

mfit_r <- function(x, Y, X, h) {
    .Call(`_jra_mfit_r`, x, Y, X, h)
}

mfit_l <- function(x, Y, X, h) {
    .Call(`_jra_mfit_l`, x, Y, X, h)
}

delta <- function(x_seq, Y, X, h) {
    .Call(`_jra_delta`, x_seq, Y, X, h)
}

detect <- function(x_seq, Y, X, h, c_h, L) {
    .Call(`_jra_detect`, x_seq, Y, X, h, c_h, L)
}

ker_c <- function(u) {
    .Call(`_jra_ker_c`, u)
}

mfit_c <- function(x, Y, X, h) {
    .Call(`_jra_mfit_c`, x, Y, X, h)
}

JIC <- function(x_seq, Y, X, h, c_h, L, gamma, adj_fac_JIC, adj_fac_BIC) {
    .Call(`_jra_JIC`, x_seq, Y, X, h, c_h, L, gamma, adj_fac_JIC, adj_fac_BIC)
}

val <- function(x_seq, Y_O, X_O, Y_E, X_E, h, c_h, L) {
    .Call(`_jra_val`, x_seq, Y_O, X_O, Y_E, X_E, h, c_h, L)
}

RSS_h <- function(jump_loc, jump_size, Y_O, X_O, Y_H, X_H, h) {
    .Call(`_jra_RSS_h`, jump_loc, jump_size, Y_O, X_O, Y_H, X_H, h)
}

sFDP <- function(W, q_all) {
    .Call(`_jra_sFDP`, W, q_all)
}

